spring:
  application:
    name: registerdemo
server:
  port: 10001 #注册中心访问端口

eureka:
  instance:
    hostname: register1 #服务运行的宿主机的名称
  client:
    register-with-eureka: true #将自己注册到别的服务器
    fetch-registry: true #去注册中心获取其他服务地址
    service-url:
      defaultZone: http://admin:admin@register2:10002/eureka,http://admin:admin@register3:10003/eureka #同时向register2/register3中的Eureka服务器注册
#Eureka服务器页面添加用户密码认证
security:
  basic:
    enabled: true
  user:
    name: admin
    password: admin
logging:
  config: classpath:logback-spring.xml #读取日志配置文件